# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 740efa0fb537a76cd268291a6cdb16880cfc12757168f2cb2246d9350312c3bc112eeb85ccec505f7d74ea46d477b33dc0a586cdd7cd9f12ae838a5efe8dfc65

test:
  secret_key_base: 2536b369eb69142a302a86afc5444d9e57b3d160b976f7fd9210fabd0696387f18857b1e3a87a3734cc74e24bf931d468637c1387009d434e6e1cb9a4005d7f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
